/**
 * Central color palette for AMD.
 * Import from here instead of hardcoding Tailwind color classes.
 */

export const palette = {
  // Brand
  brand: {
    primary:   "blue-600",
    secondary: "indigo-600",
    accent:    "violet-500",
    gradient:  "from-blue-500 to-indigo-600",
  },

  // Surfaces — light / dark pairs (light, dark)
  surface: {
    app:       { light: "gray-50",  dark: "gray-950" },
    sidebar:   { light: "white",    dark: "gray-950" },
    card:      { light: "white",    dark: "gray-900" },
    input:     { light: "white",    dark: "gray-800" },
    elevated:  { light: "gray-100", dark: "gray-800" },
    overlay:   { light: "gray-200", dark: "gray-800" },
  },

  // Borders
  border: {
    subtle:  { light: "gray-200",  dark: "gray-800" },
    default: { light: "gray-300",  dark: "gray-700" },
  },

  // Text
  text: {
    primary:   { light: "gray-900", dark: "gray-100" },
    secondary: { light: "gray-600", dark: "gray-400" },
    muted:     { light: "gray-400", dark: "gray-600" },
    inverse:   { light: "white",    dark: "gray-900" },
  },

  // Status
  status: {
    success:  "emerald-500",
    warning:  "amber-500",
    error:    "red-500",
    info:     "blue-500",
    running:  "green-400",
    paused:   "amber-400",
    finished: "blue-400",
    failed:   "red-500",
    idle:     "gray-600",
  },

  // Interactive
  interactive: {
    hover:     { light: "gray-100",  dark: "gray-800" },
    active:    { light: "gray-200",  dark: "gray-700" },
    focus:     "blue-500",
    danger:    "red-600",
    dangerHv:  "red-500",
  },
} as const;

/**
 * Runtime colors for canvas/WebGL/Plotly consumers that cannot use Tailwind
 * classes. These values intentionally mirror the palette already used by the
 * interface so DOM UI and generated graphics stay visually related.
 */
export const UI_COLORS = {
  brand: {
    primary: "#60a5fa",   // blue-400
    secondary: "#818cf8", // indigo-400
    accent: "#a78bfa",    // violet-400
    science: "#67e8f9",   // cyan-300
  },
  status: {
    success: "#10b981", // emerald-500
    warning: "#f59e0b", // amber-500
    danger: "#ef4444",  // red-500
    info: "#3b82f6",    // blue-500
  },
  neutral: {
    50: "#f9fafb",
    100: "#f3f4f6",
    200: "#e5e7eb",
    300: "#d1d5db",
    400: "#9ca3af",
    500: "#6b7280",
    600: "#4b5563",
    700: "#374151",
    800: "#1f2937",
    900: "#111827",
    950: "#030712",
  },
  plot: {
    series: [
      "#67e8f9", // arc cyan
      "#7dd3fc", // arc sky
      "#818cf8", // arc indigo
      "#c4b5fd", // arc violet
      "#10b981", // emerald
      "#f59e0b", // amber
      "#ec4899", // pink
      "#ef4444", // red
    ],
    energy: {
      potential: "#f59e0b",
      kinetic: "#38bdf8",
      total: "#a78bfa",
      temperature: "#ef4444",
      pressure: "#10b981",
    },
  },
} as const;

export function colorWithAlpha(hex: string, alpha: number): string {
  const normalized = hex.replace("#", "");
  if (!/^[0-9a-f]{6}$/i.test(normalized)) return hex;
  const value = Number.parseInt(normalized, 16);
  const red = (value >> 16) & 255;
  const green = (value >> 8) & 255;
  const blue = value & 255;
  return `rgba(${red}, ${green}, ${blue}, ${alpha})`;
}

export function viewerBackground(theme: "light" | "dark"): string {
  return theme === "dark" ? UI_COLORS.neutral[900] : "#ffffff";
}

/**
 * 100 distinct CV colors derived from the brand palette.
 * Generated by rotating hue in steps around the color wheel, with
 * alternating saturation/lightness to maximize visual distinction.
 *
 * Base hues anchored on: amber(38), sky(198), violet(270), emerald(155),
 * pink(330), orange(25), indigo(234), cyan(188) — matching the original 8.
 */
export const CV_PALETTE: string[] = (() => {
  const colors: string[] = [];

  // 10 base hues evenly spaced, each with 10 lightness/saturation variants = 100
  const baseHues = [
    38,   // amber
    198,  // sky
    270,  // violet
    155,  // emerald
    330,  // pink
    25,   // orange
    234,  // indigo
    188,  // cyan
    70,   // lime
    0,    // red
  ];

  const satLightPairs: [number, number][] = [
    [85, 55],  // vivid mid
    [75, 45],  // deep
    [90, 65],  // bright
    [65, 40],  // dark
    [80, 60],  // standard
    [70, 50],  // muted mid
    [95, 70],  // pastel-bright
    [60, 35],  // very dark
    [85, 75],  // light
    [75, 55],  // balanced
  ];

  for (let i = 0; i < 100; i++) {
    const hueIdx = i % 10;
    const varIdx = Math.floor(i / 10);
    // Offset each hue ring slightly so adjacent CVs don't share a hue
    const hue = (baseHues[hueIdx] + varIdx * 7) % 360;
    const [sat, light] = satLightPairs[varIdx];
    colors.push(`hsl(${hue}, ${sat}%, ${light}%)`);
  }

  return colors;
})();

/** Semantic CSS variable names used in globals.css for theme switching. */
export const cssVars = {
  bg:         "--color-bg",
  bgCard:     "--color-bg-card",
  bgInput:    "--color-bg-input",
  bgElevated: "--color-bg-elevated",
  border:     "--color-border",
  borderSub:  "--color-border-subtle",
  text1:      "--color-text-primary",
  text2:      "--color-text-secondary",
  text3:      "--color-text-muted",
  scrollThumb:    "--color-scroll-thumb",
  scrollThumbHv:  "--color-scroll-thumb-hover",
} as const;
